server:
  port: 8761
spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: discovery-server
      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false